[http]
address = "0.0.0.0"
port = 3001

[tracing]
level="DEBUG"

[tracing.rolling_file]
directory = "./logs"
prefix = "log"
rotation = "DAILY"

[database]
url = "postgres://postgres:postgres@localhost:5432/test"
max_connection = 10

[redis]
url = "redis://localhost"